### ISSUE TITLE
runtime error: slice bounds out of rang

### ISSUE THREAD

**Issue by left2right** [seefan/gossdb#19]
panic: runtime error: slice bounds out of range

goroutine 1819 [running]:
panic(0x4b46c0, 0xc820010080)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/ssdb/gossdb/ssdb.(*Client).parse(0xc82009c4d0, 0x0, 0x0, 0x0)
	/Users/left2right/go/src/github.com/ssdb/gossdb/ssdb/ssdb.go:146 +0x52f
github.com/ssdb/gossdb/ssdb.(*Client).recv(0xc82009c4d0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/left2right/go/src/github.com/ssdb/gossdb/ssdb/ssdb.go:132 +0x86
github.com/ssdb/gossdb/ssdb.(*Client).Do(0xc82009c4d0, 0xc8209b9d30, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/left2right/go/src/github.com/ssdb/gossdb/ssdb/ssdb.go:34 +0xb4
github.com/seefan/gossdb.(*Client).Do(0xc82009c4d0, 0xc8209b9d30, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/left2right/go/src/github.com/seefan/gossdb/client.go:160 +0x407
github.com/seefan/gossdb.(*Client).qpush(0xc82009c4d0, 0xc820edf2f0, 0x2f, 0x1, 0xc8209b9e60, 0x1, 0x1, 0xc820d10af0, 0x0, 0x0)
	/Users/left2right/go/src/github.com/seefan/gossdb/queue.go:76 +0x3b1
github.com/seefan/gossdb.(*Client).Qpush(0xc82009c4d0, 0xc820edf2f0, 0x2f, 0xc8209b9e60, 0x1, 0x1, 0x1, 0x0, 0x0)
	/Users/left2right/go/src/github.com/seefan/gossdb/queue.go:93 +0x73
main.SsdbStoreMessageLog(0xc820616ff0)

**Comment by seefan** [comment]
你好，能给出传入的参数么？

**Comment by left2right** [comment]
不好意思，这么久没有回复你，被别的事情岔开了，抱歉。
func GetSsdbClient() *gossdb.Client {
	c, err := SsdbPool.NewClient()
	if err != nil {
		log.Error(err.Error)
		return nil
	}
	defer c.Close()
	return c
}

GetSsdbClient().Qpush(key, string(message.Value))
看log就是从这个地方报的错，这样使用有问题吗？多谢

**Comment by left2right** [comment]
Ps：我的使用方法是建立比较大的连接池如5000个连接，每个来的请求使用goroutine获取一个连接，然后操作数据库，但这有个问题是如果瞬间压力很大，连接数不够用，这时再调用NewClient()，如何判断有没有可用的连接，做下限制，如等待下再获取？

**Comment by seefan** [comment]
你的defer使用的是错的，函数执行完后c就被关闭了，再执行qpush当然报错，请合并到一个函数。

**Comment by left2right** [comment]
thx
