### ISSUE TITLE
请问有人在生产环境中使用此driver 吗？

### ISSUE THREAD

**Issue by slw2011** [seefan/gossdb#25]

**Comment by seefan** [comment]
我自己用了，其它的我还不清楚。

**Comment by slw2011** [comment]
ok,  你们的请求量大吗？ 多少qps？

**Comment by seefan** [comment]
非http，大约几百G数据

**Comment by slw2011** [comment]
请问你们数据有几百GB有做主从同步吗？如果做了，应该会出现主从同步不上的问题，搜索了解决办法，ssdb作者说将接收队列长度改得更大，1亿就可以解决，试了一下，确实可以同步上，但是还是有问题，磁盘io持续很高，SSD机器都扛不住了，只能清理过期数据，减小ssdb大小。

**Comment by seefan** [comment]
我们确认没有用主从，我们是监控数据，用完过期就删除了
