### ISSUE TITLE
最新版问题

### ISSUE THREAD

**Issue by wwwjyl** [seefan/gossdb#26]
client.SSDBClient需要添加Ping函数，现在有两个IClient （client  和 gopoil目录中）

balance/balance.go:109: cannot use client.SSDBClient literal (type *client.SSDBClient) as type gopool.IClient in return argument:
        *client.SSDBClient does not implement gopool.IClient (missing Ping method)

**Comment by seefan** [comment]
是的，最新版还没有完成，如果使用请从release里取https://github.com/seefan/gossdb/releases/tag/v1.0

**Comment by seefan** [comment]
ping函数加上了
