### ISSUE TITLE
用zrrange取出的map有时不按顺序排列

### ISSUE THREAD

**Issue by youmisun** [seefan/gossdb#29]
map[10:863199410872 9:433702681372 11:433702628072]
map[10:863199410872 9:433702681372 11:433702628072]
map[9:433702681372 11:433702628072 10:863199410872]
map[10:863199410872 9:433702681372 11:433702628072]
map[9:433702681372 11:433702628072 10:863199410872]
map[10:863199410872 9:433702681372 11:433702628072]
用zrrange取出的map。上面的数据取自同一个zset, zset没有数据插入和更新。
下面是直接用ssdb命令取的结果是保持每次都是有序的。
ssdb 127.0.0.1:18888> zrrange gamescore:15 0 3
key             value
-------------------------
  10             : 863199410872
  9              : 433702681372
  11             : 433702628072
3 result(s) (0.001 sec)
(0.001 sec)

**Comment by seefan** [comment]
是的，map里的kv是无序的。如果需要结果是有序的，请不要使用zrrange，使用zrrange_slice
