### ISSUE TITLE
MultiGet、MultiGetSlice、MultiGetArray等接口均报类型错误

### ISSUE THREAD

**Issue by stitchcula** [seefan/gossdb#30]
例如
`cli.MultiGetSlice("a", "b")`
会报“the trace error is bad arguments type”。
经查看实现，内部没有对args进行解构，导致do的时候传入的是
`[multi_get [ ]]`
导致类型判断出错。
望修复。

**Comment by seefan** [comment]
确实存在这个问题，已修正。

**Comment by mitiger** [comment]
同样报错， 出现在Qpush等操作里面 ，是不是同样的问题？
