### ISSUE TITLE
ssdb set 永远不超时

### ISSUE THREAD

**Issue by fly512** [seefan/gossdb#33]
如题，见下面， IO wait, 83 minutes， 有很多这样的，重启下 ssdb server 就好了
`goroutine 27972 [IO wait, 83 minutes]:
internal/poll.runtime_pollWait(0x7fb6a7865eb0, 0x72, 0x0)
	/home/soft/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420012598, 0x72, 0xffffffffffffff00, 0xda2360, 0xd9d708)
	/home/soft/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420012598, 0xc42017f000, 0x1000, 0x1000)
	/home/soft/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420012580, 0xc42017f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/soft/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc420012580, 0xc42017f000, 0x1000, 0x1000, 0x7, 0x0, 0x0)
	/home/soft/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc42000e6a8, 0xc42017f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/soft/go/src/net/net.go:176 +0x6d
bufio.(*Reader).fill(0xc420052fc0)
	/home/soft/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).ReadSlice(0xc420052fc0, 0xa002017f00a, 0x38, 0x40, 0xc420ffca80, 0x7fb6a7897e18, 0x0)
	/home/soft/go/src/bufio/bufio.go:338 +0x2c
bufio.(*Reader).ReadBytes(0xc420052fc0, 0xa, 0x1, 0x0, 0x0, 0xc420ffca80, 0x2)
	/home/soft/go/src/bufio/bufio.go:416 +0x6b
github.com/seefan/gossdb.(*SSDBClient).Recv(0xc42008c840, 0xc420597458, 0x2, 0x2, 0x0, 0x0)
	/home/soft/gopath/src/github.com/seefan/gossdb/ssdbclient.go:197 +0x72
github.com/seefan/gossdb.(*SSDBClient).do(0xc42008c840, 0xc420597458, 0x2, 0x2, 0xc4205972a8, 0xc4205972e8, 0x877011, 0xc420140158, 0xc420597358)
	/home/soft/gopath/src/github.com/seefan/gossdb/ssdbclient.go:59 +0x9c
github.com/seefan/gossdb.(*SSDBClient).Do(0xc42008c840, 0xc420597458, 0x2, 0x2, 0x10, 0x9b3d00, 0xc420df2001, 0xc4216679b0, 0xc420272478)
	/home/soft/gopath/src/github.com/seefan/gossdb/ssdbclient.go:79 +0x74
github.com/seefan/gossdb.(*Client).Do(0xc4200c77c0, 0xc420597458, 0x2, 0x2, 0x5c, 0x412397, 0x7fb6a78692a8, 0x465992, 0x0)
	/home/soft/gopath/src/github.com/seefan/gossdb/client.go:46 +0x50
github.com/seefan/gossdb.(*Client).Get(0xc4200c77c0, 0xc4202724b0, 0xd, 0x4d2934, 0xc4205974f0, 0x42be79, 0xc400000008)
	/home/soft/gopath/src/github.com/seefan/gossdb/set.go:51 +0xf7
main/app/model.(*ssdbCache).Get(0xc4205975d0, 0x9982a0, 0xc420a85ce0, 0x1, 0x1)`

**Comment by fly512** [comment]
Ubuntu 14.04.5 LTS (GNU/Linux 4.9.36-x86_64-linode85 x86_64)
go version go1.9 linux/amd64

**Comment by fly512** [comment]
还有一种这样的
`internal/poll.runtime_Semacquire(0xc420ba8d08)
	/home/soft/go/src/runtime/sema.go:61 +0x39
internal/poll.(*fdMutex).rwlock(0xc420ba8d00, 0x1, 0xc420604f20)
	/home/soft/go/src/internal/poll/fd_mutex.go:152 +0xad
internal/poll.(*FD).readLock(0xc420ba8d00, 0xc42090aa00, 0xc420604f20)
	/home/soft/go/src/internal/poll/fd_mutex.go:219 +0x36
internal/poll.(*FD).Read(0xc420ba8d00, 0xc4214e8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/soft/go/src/internal/poll/fd_unix.go:102 +0x4d
net.(*netFD).Read(0xc420ba8d00, 0xc4214e8000, 0x1000, 0x1000, 0x0, 0x0, 0xc420605058)
	/home/soft/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc423396b08, 0xc4214e8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/soft/go/src/net/net.go:176 +0x6d
bufio.(*Reader).fill(0xc42334ce40)
	/home/soft/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).ReadSlice(0xc42334ce40, 0xc42060510a, 0x44c9e6, 0xd90c9a, 0xc237, 0xc237, 0xaa700000002)
	/home/soft/go/src/bufio/bufio.go:338 +0x2c
bufio.(*Reader).ReadBytes(0xc42334ce40, 0xe22d0a, 0xc420605248, 0x42c538, 0x251145, 0x94ab8e, 0x4cf8fc)
	/home/soft/go/src/bufio/bufio.go:416 +0x6b
github.com/seefan/gossdb.(*SSDBClient).Recv(0xc420ef84d0, 0xc420605458, 0x2, 0x2, 0x0, 0x0)
	/home/soft/gopath/src/github.com/seefan/gossdb/ssdbclient.go:197 +0x72
github.com/seefan/gossdb.(*SSDBClient).do(0xc420ef84d0, 0xc420605458, 0x2, 0x2, 0xc4206052a8, 0xc4206052e8, 0x877011, 0xc420140158, 0xc420605358)
	/home/soft/gopath/src/github.com/seefan/gossdb/ssdbclient.go:59 +0x9c
github.com/seefan/gossdb.(*SSDBClient).Do(0xc420ef84d0, 0xc420605458, 0x2, 0x2, 0x10, 0x9b3d00, 0xc420ada101, 0xc420bdb720, 0xc420f57c58)
	/home/soft/gopath/src/github.com/seefan/gossdb/ssdbclient.go:79 +0x74
github.com/seefan/gossdb.(*Client).Do(0xc4212e2700, 0xc420605458, 0x2, 0x2, 0x62, 0x412397, 0x7fb6a78139c8, 0x465992, 0x0)
	/home/soft/gopath/src/github.com/seefan/gossdb/client.go:46 +0x50
github.com/seefan/gossdb.(*Client).Get(0xc4212e2700, 0xc420f57c70, 0xb, 0x4d2934, 0xc4206054f0, 0x42be79, 0xc400000008)
	/home/soft/gopath/src/github.com/seefan/gossdb/set.go:51 +0xf7`

**Comment by seefan** [comment]
麻烦提供下gossdb的版本号，和ssdb的版本号，如果有ssdb的日志，最好也能提供一下。目前看是取数据时无法取到，引起超时。

**Comment by fly512** [comment]
gossdb 版本号，我没找到，从git库中看，我本地git提交如下
`
commit be37db68dc833b1156b4f3b3a42bff946a9bce33
Author: zng <zhang.naiguo@xcar.com.cn>
Date:   Mon Aug 28 11:40:27 2017 +0800
 修复multi函数参数传递bug
`

ssdb 版本 ssdb-server 1.9.4

连接池配置 
`		Host:             config.SsdbHost,
		Port:             config.SsdbPort,
		MinPoolSize:      10,
		MaxPoolSize:      100,
		AcquireIncrement: 5,
		GetClientTimeout: 1,`

ssdb 日志稍等

**Comment by seefan** [comment]
确认一下

1. client的连接是不是在goroutine里打开的，同时goroutine也有连接的关闭。这个主要是确认是不是有锁的问题。
2、goroutine的数量是不是有最大值限制，还是没有限制。

**Comment by fly512** [comment]
1、client的连接 是在 goroutine 打开，也在goroutine关闭
2、有最大限制，50个

**Comment by seefan** [comment]
这样可能比较难找问题了，把ssdb的日志开到debug，有日志继续分析吧。目前gossdb支持10000qps是可以稳定运行的，有线上的项目验证过。

后面主要查两个地方：
1、ssdb的日志，是什么导致ssdb没有响应。
2、gossdb的协议解析，目前是在读取一行数据时出的错，需要查这块是什么原因。

**Comment by fly512** [comment]
这个不是set出错，只是set.go 的 Get 调用出错
`func (c *Client) Get(key string) (Value, error) {
	resp, err := c.Do("get", key)
	if err != nil {
		return "", goerr.NewError(err, "Get %s error", key)
	}
	if len(resp) == 2 && resp[0] == "ok" {
		return Value(resp[1]), nil
	}
	return "", makeError(resp, key)
}`

**Comment by seefan** [comment]
是这个函数错的错bufio.(*Reader).ReadSlice，也就是从ssdb读数据出来的时候超时了。

你目前用的gossdb最新的版本，建议你可以使用release版本再测试一下，看看是不是gossdb的问题。
https://github.com/seefan/gossdb/releases
在这里下载

**Comment by fly512** [comment]
好的，晚上试一试

**Comment by fly512** [comment]
貌似还有问题

> goroutine 314639 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f8873fff480, 0x72, 0x0)
	/home/soft/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42250b418, 0x72, 0xffffffffffffff00, 0xdaf420, 0xdaa708)
	/home/soft/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42250b418, 0xc421fd7000, 0x1000, 0x1000)
	/home/soft/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42250b400, 0xc421fd7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/soft/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc42250b400, 0xc421fd7000, 0x1000, 0x1000, 0x104, 0x2, 0xc422cfd418)
	/home/soft/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc4222e7860, 0xc421fd7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/soft/go/src/net/net.go:176 +0x6d
bufio.(*Reader).fill(0xc422891c20)
	/home/soft/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).ReadSlice(0xc422891c20, 0xc421fd710a, 0x1, 0xc4203bcfe4, 0x1, 0x1, 0x0)
	/home/soft/go/src/bufio/bufio.go:338 +0x2c
bufio.(*Reader).ReadBytes(0xc422891c20, 0xc4203bcf0a, 0x1, 0x1, 0x1, 0x0, 0x0)
	/home/soft/go/src/bufio/bufio.go:416 +0x6b
github.com/seefan/gossdb.(*SSDBClient).Recv(0xc42008cf20, 0xc422cfd810, 0x2, 0x2, 0x0, 0x0)
	/home/soft/gopath/src/github.com/seefan/gossdb/ssdbclient.go:196 +0xa7
github.com/seefan/gossdb.(*SSDBClient).do(0xc42008cf20, 0xc422cfd810, 0x2, 0x2, 0xc4205bbe80, 0x7f88706f9c8d, 0x87ce01, 0x1e8, 0xc422cfd710)
	/home/soft/gopath/src/github.com/seefan/gossdb/ssdbclient.go:60 +0x9c
github.com/seefan/gossdb.(*SSDBClient).Do(0xc42008cf20, 0xc422cfd810, 0x2, 0x2, 0xc4205bbe80, 0xc4203bcfa0, 0xc422c8ad01, 0xc4205bbe80, 0xc4205bbe80)
	/home/soft/gopath/src/github.com/seefan/gossdb/ssdbclient.go:80 +0x74
github.com/seefan/gossdb.(*Client).Do(0xc4200c7b60, 0xc422cfd810, 0x2, 0x2, 0x4133c6, 0xc422cfd790, 0xc4200eb880, 0x456c90, 0xc4200eb880)
	/home/soft/gopath/src/github.com/seefan/gossdb/client.go:46 +0x50
github.com/seefan/gossdb.(*Client).Get(0xc4200c7b60, 0xc4203bcfa0, 0xb, 0x4d2934, 0xc422cfd8a8, 0x42be79, 0xc4249bbd18)
	/home/soft/gopath/src/github.com/seefan/gossdb/set.go:51 +0xf7
main/app/model.(*ssdbCache).Get(0xc422cfd988, 0x9a08a0, 0xc42165f420, 0x1, 0x1)

**Comment by seefan** [comment]
有时间你写一个测试例发上来吧，我在我这里测试一下，最好发和部分数据样例。

我这边连续跑一个小时，也没有发现这个问题。

**Comment by seefan** [comment]
这个问题是出在从ssdb中读取数据，出这个问题有两种可能。一是数据包解析有问题，导致读取不存在的数据，所以会一直等待到超时。另外就ssdb里有出了问题，或是网络出了问题，导致连接中断一直到超时。

**Comment by seefan** [comment]
可能是在包解析上的问题，已重写了解析方法，可以再测试一下。

**Comment by seefan** [comment]
与#32类型的问题
