### ISSUE TITLE
Hincr 连接好像串包了

### ISSUE THREAD

**Issue by slw2011** [seefan/gossdb#36]
我们正式环境的服务器，之前存储的消息量小余13GByte 时，没有任何问题，但是最近两天频繁出现Hinc失败，没有返回错误，因为有响应，然后响应的长度大于2，所以Hinc之后的返回值为-1， 但是没有任何错误。以下为两次的结果，好像串包了。貌似info命令和get命令了。请问您之前是否有碰到呢？
附加信息：我用的是你master 分支的0394129 这个版本的driver，这个版本使用的仍然是ideawu官方的go语言driver。

Hinc hashName=8019915#gmsg key=0 num=1 err=access ssdb error, code is [ok ssdb-server version 1.9.4 links 120 total_calls 1223109 dbsize 13026765809 binlogs     capacity : 100000000

ssdbOperator.Hinc failed err=access ssdb error, code is [ok 68856_1507898802415_7624782ΰ���� *�x�lP͊�0~�a.{�l˖�[)K��-�՚$"��Jʺ!���������tO��|3����YY�

**Comment by seefan** [comment]
这个建议同时反馈到ssdb，看看ideawu怎么说。

**Comment by slw2011** [comment]
qps 大概是是160次/s，感觉应该是当某次读取出错之后，使用你的连接池，没有立即关闭连接，也没有清空缓冲区，那么下次再发送命令之后，读取响应，得到的必然不是当前命令的响应。

**Comment by seefan** [comment]
160次不高，client读取出错时，会关闭连接，不会放回连接池时，所以应该不是缓冲区的问题。有可能的话，打开ssdb的日志记录。

**Comment by slw2011** [comment]
这个版本使用的仍然是ideawu官方的go语言driver, 那个版本应该是使用info命令来保持连接存活，刚刚Hincr 的响应，明显是info命令的响应，所以应该是发送Hincr命令之后，读取响应的时候，原来缓冲区还有上次没有读取的info命令的响应。“client读取出错时，会关闭连接，不会放回连接池”，那应该也不会是读取出错了，可能是info命令发送成功了，但是没有读完全部响应吧？

**Comment by slw2011** [comment]
刚刚搜索了一下，好像没有看到你读取出错调用关闭socket连接的方，麻烦指导一下。

**Comment by seefan** [comment]
修复了一个连接池中的bug，解决了串包的问题。
