### ISSUE TITLE
请问如何设置NewPool()这个函数的超时时间？

### ISSUE THREAD

**Issue by mitiger** [seefan/gossdb#39]
NewPool()这个函数的超时如何设置？  我尝试设置GetClientTimeout  这个变量，好像丝毫没有效果

**Comment by seefan** [comment]
你问的是哪个超时，GetClientTimeout只是在获取连接时有用，超过这个时间获取不到连接就返回error。至于连接ssdb的超时时间目前用的是默认的。

**Comment by mitiger** [comment]
我希望用NewPool这个超时， 因为如果我配置文件里面配置的IP写错了， 就会阻塞好久， 不太好

**Comment by seefan** [comment]
目前还没有这个设置，我看看怎么加

**Comment by seefan** [comment]
已解决
