### ISSUE TITLE
~  go get github.com/seefan/gossdb

### ISSUE THREAD

**Issue by sundy-li** [seefan/gossdb#4]
➜  ~  go get github.com/seefan/gossdb
# github.com/seefan/gossdb
gopath/src/github.com/seefan/gossdb/connectors.go:68: syntax error: unexpected range, expecting {
gopath/src/github.com/seefan/gossdb/connectors.go:72: non-declaration statement outside function body
gopath/src/github.com/seefan/gossdb/connectors.go:73: syntax error: unexpected }

**Comment by seefan** [comment]
我重新下载了一下，并没有你提到的问题，请检查一下网络，是不是没有下载完整。
