### ISSUE TITLE
最新的代码 ， QPUSH相关操作会有问题

### ISSUE THREAD

**Issue by mitiger** [seefan/gossdb#40]
使用Qpush_back等操作的时候，会出现
the trace error is
client send error
the trace error is
bad arguments type

设置了 gossdb.Encoding = true后， 出现
access ssdb error, code is [client_error wrong number of arguments], parameter is [list1]

使用之前的版本代码库， 就没有问题

**Comment by seefan** [comment]
代码问题，已解决

**Comment by kaixinbuyu** [comment]
最新的代码，仍旧还是报这个错。

**Comment by seefan** [comment]
你用example里测试queue的test试一下，然后发我一下ssdb的版本，我在本地测试没有发现你的问题了。原来确实是有问题，但已修正了。

你也可以对比一下你下载的代码和github上的代码，看看是不是有不一样的地方。

**Comment by seefan** [comment]
另外，你把你的测试代码发上来，我研究一下。

**Comment by kaixinbuyu** [comment]
已解决，是老的wrapper类没有改干净。现在的版本本身没问题了。谢谢。
