### ISSUE TITLE
连接数不够用

### ISSUE THREAD

**Issue by mitiger** [seefan/gossdb#41]
并发量大的情况下， 连接数会不够用
![image](https://user-images.githubusercontent.com/1697699/32162364-afea71a0-bd93-11e7-87f6-d5ecb0190536.png)

我已经设置了MaxPoolSize=500
感觉像是连接没有释放， 但是 我有在每个操作之后， 都去调用Close方法
![image](https://user-images.githubusercontent.com/1697699/32162344-a11c6ffc-bd93-11e7-80c0-f3ca6d522c86.png)

**Comment by mitiger** [comment]
一开始报的错是  get client error  ， 跑一段时间之后，就变成Pool is busy了

**Comment by seefan** [comment]
这种情况是因为瞬间并发太高造成的，你可以控制一下你的并发量再试一下。
