### ISSUE TITLE
当ssdb服务器重启后，会大量pool is busy,can not get new client in x seconds

### ISSUE THREAD

**Issue by RDchengbiao** [seefan/gossdb#47]
在从连接池中取client时候是不是没有判断该连接的可用状态？比如高并发情况下，重启ssdb服务器，会出现大量pool is busy,can not get new client in x seconds的错误，这是什么情况呢？

**Comment by seefan** [comment]
非bug，是要你的连接全部占用，并且排队也超过限制时，会报这个提示

**Comment by seefan** [comment]
//最大连接池个数。默认值: 20
	MaxPoolSize int
	//最小连接池数。默认值: 5
	MinPoolSize int
	//当连接池中的连接耗尽的时候一次同时获取的连接数。默认值: 5
	AcquireIncrement int
	//最大等待数目，当连接池满后，新建连接将等待池中连接释放后才可以继续，本值限制最大等待的数量，超过本值后将抛出异常。默认值: 1000
可以通过修改这3个参数调整

**Comment by RDchengbiao** [comment]
高并发下，当重启ssdb服务器后，netstat 后发现并没有任何连接到ssdb的连接。p.pooled里的连接已经并不可用了吧？ 这时候还认为连接池已经满了？

**Comment by seefan** [comment]
ssdb重启后，连接会在几秒后断开连接并重连，这个由下面的参数控制
//连接池内缓存的连接状态检查时间隔，单位为秒。默认值: 5
HealthSecond int
//是否启用重试，设置为true时，如果请求失败会再重试一次。
RetryEnabled bool

**Comment by seefan** [comment]
ssdb重启，连接池并不知道，需要时间进行重置

**Comment by RDchengbiao** [comment]
ssdb重启，连接池中缓存的连接是否还跟ssdb是已连接状态也没有判断吧？ checkPool中： if s.length > s.minPoolSize && pos > s.current && s.pooled[pos] != nil && !s.pooled[pos].isUsed && s.pooled[pos].lastTime+hs < now {} 这里没有判断连接目前是否可用吧？

**Comment by seefan** [comment]
连接状态是在别一个轮询的协程里检查的，不是在每次取连接时检查，那样太占时间了。
ssdb重启后，连接池中的连接目前没有找到直接的回调可以知道是否可用，只有在使用时出错才能发现连接不可用。
如果你有方法，我很愿意加到gossdb里

**Comment by RDchengbiao** [comment]
我上面的两个评论提到的问题，就是在watch协程里的。当等待连接的数量不是0的时候，缓存的连接状态根本不会被check到吧？ 那么checkMinPoolClient和checkPool都不会被执行吧？

**Comment by seefan** [comment]
是的，正在使用的连接不会被检查，一但执行出错，回收时会被销毁，所以后续会再创建新的连接代替它

**Comment by seefan** [comment]
解决方法，在连接不可用后，不再进入连接池等待检查，而是直接关闭掉，给新建连接腾出位置。
