### ISSUE TITLE
连续c.Close()导致报错

### ISSUE THREAD

**Issue by sunzhy** [seefan/gossdb#48]
使用连接池
上层方法手误连续写了两个**defer c.Close()**
第一次请求正常，之后的请求报错：
2019-03-06 16:59:52.367 error   runtime error: index out of range
2019-03-06 16:59:52.367 error   goroutine 49 [running]:
runtime/debug.Stack(0xc000545168, 0x1, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
jqdataserver2/routers.post.func1.1(0xc00026e000)
        /home/server/go/src/jqdataserver2/routers/router.go:84 +0x7f
panic(0xb07fc0, 0x1315900)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/seefan/gossdb/vendor/github.com/seefan/gopool.(*Slice).Get(0xc0000a4c30, 0x0, 0x0, 0x0)
        /home/server/go/src/github.com/seefan/gossdb/vendor/github.com/seefan/gopool/slice.go:101 +0x133
github.com/seefan/gossdb/vendor/github.com/seefan/gopool.(*Pool).Get(0xc000115080, 0xc0005453e0, 0x0, 0xc0001c4180)
        /home/server/go/src/github.com/seefan/gossdb/vendor/github.com/seefan/gopool/pool.go:150 +0x5b
github.com/seefan/gossdb.(*Connectors).NewClient(0xc00017afa0, 0xc0001bf080, 0xbe1f23, 0xc)
        /home/server/go/src/github.com/seefan/gossdb/connectors.go:86 +0x3b

打印信息发现：
pool size:50    actived client:-1       wait create:0   config max pool size:5000
actived client是-1

感觉在Close()方法可以优化一下

**Comment by seefan** [comment]
已增加防止重复关闭的标记，可以防止此类崩溃。你重复调用close，潜在的问题是关闭了被别人重新打开的连接，所以还是尽量避免此类写法。
