### ISSUE TITLE
设置密码之后，get 总是报 authentication failed

### ISSUE THREAD

**Issue by lintingyong** [seefan/gossdb#50]
![image](https://user-images.githubusercontent.com/22091910/57846805-9ae03580-7807-11e9-96b2-0ae113bfd9f5.png)
![image](https://user-images.githubusercontent.com/22091910/57846972-f5799180-7807-11e9-8e1e-2a0a082186a7.png)

是我用法不对吗？谢谢解答

**Comment by lintingyong** [comment]
refs/remotes/origin/master 1735a3276095f54e3cf70727474d234d4178611d

**Comment by lintingyong** [comment]
![image](https://user-images.githubusercontent.com/22091910/57848735-31165a80-780c-11e9-9ad2-a108a44cc8a3.png)
我在这里加了一种类型的 case 判断之后，问题解决了，我发现在做密码验证 auth 时，传过来的参数是 []string 类型

**Comment by lintingyong** [comment]
我试了下另外一种修改 bug 的方式，也是可行的
![image](https://user-images.githubusercontent.com/22091910/57851543-683c3a00-7813-11e9-839a-949fb6a8bec1.png)

**Comment by seefan** [comment]
修改了协议解析那块的代码，这里漏掉了，已修正

**Comment by lintingyong** [comment]
好的，谢谢



------------------ 原始邮件 ------------------
发件人: "seefan"<notifications@github.com>; 
发送时间: 2019年5月16日(星期四) 晚上8:47
收件人: "seefan/gossdb"<gossdb@noreply.github.com>; 
抄送: "oneminuter"<1050086935@qq.com>; "Manual"<manual@noreply.github.com>; 
主题: Re: [seefan/gossdb] 设置密码之后，get 总是报 authentication failed (#50)




修改了协议解析那块的代码，这里漏掉了，已修正
