### ISSUE TITLE
获取大的 value，获取不到

### ISSUE THREAD

**Issue by GZJmy** [seefan/gossdb#51]
作者，您好，我存了一个 8M 左右的 value， 但是我在程序客户端 Get 不到这个 value，每次取出来的都是空字符串，请指教

**Comment by seefan** [comment]
已经确认是个bug，昨天晚上临时修复了，最近几天会集中解决这个问题

**Comment by GZJmy** [comment]
目前可以取到这个比较大的 value，但是时间有点久

**Comment by seefan** [comment]
可以将ReadBufferSize 加大一点默认为8k

**Comment by GZJmy** [comment]
问题解决，多谢！
