### ISSUE TITLE
go get (go mod) 获取到的是 旧版本

### ISSUE THREAD

**Issue by vmvz** [seefan/gossdb#52]
请问这个问题如何解决?谢谢
![image](https://user-images.githubusercontent.com/1652700/79702809-0b29ed80-82da-11ea-8255-b5c0b2acd038.png)

**Comment by seefan** [comment]
是的，你可以通过go get获取最新的版本

**Comment by zut** [comment]
@seefan 希望能发布版本,这样方便大家mod调用呀.

**Comment by vmvz** [comment]
希望能发布到 releases中, 方便大家更新调用, 谢谢

**Comment by seefan** [comment]
还在测试中，通过后会发布的

**Comment by yxlwfds** [comment]
test中 go mod方式是错的:
# command-line-arguments
./main.go:19:3: unknown field 'PoolSize' in struct literal of type conf.Config
./main.go:22:3: unknown field 'AutoClose' in struct literal of type conf.Config
./main.go:45:12: p.GetClient undefined (type *gossdb.Connectors has no field or method GetClient)
./main.go:47:19: p.GetClient undefined (type *gossdb.Connectors has no field or method GetClient)
./main.go:64:9: undefined: gossdb.Start
./main.go:71:8: undefined: gossdb.Shutdown
./main.go:72:12: undefined: gossdb.NewClient
./main.go:88:12: undefined: gossdb.Start
./main.go:92:8: undefined: gossdb.Shutdown
./main.go:95:28: missing argument to conversion to gossdb.Client: gossdb.Client()
./main.go:95:28: too many errors

**Comment by yxlwfds** [comment]
go1.15 go get -u github.com/seefan/gossdb
之后
# go get -u github.com/seefan/gossdb
go: github.com/seefan/goerr upgrade => v1.1.2
go: github.com/seefan/gopool upgrade => v1.0.1
go: downloading github.com/seefan/goerr v1.1.2
go: downloading github.com/seefan/gopool v1.0.1
# github.com/seefan/gossdb
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/client.go:76:10: undefined: goerr.New
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/client.go:83:10: undefined: goerr.New
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/client.go:85:10: undefined: goerr.New
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/connectors.go:61:10: undefined: goerr.New
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/connectors.go:89:15: undefined: goerr.New
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/connectors.go:99:15: undefined: goerr.New
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/hset.go:14:10: undefined: goerr.NewError
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/hset.go:32:14: undefined: goerr.NewError
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/hset.go:48:10: undefined: goerr.NewError
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/hset.go:65:17: undefined: goerr.NewError
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/hset.go:65:17: too many errors
[root@izrj9ae0538vfzkozm32m9z ssdbmain]# go run main.go 
# github.com/seefan/gossdb
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/client.go:76:10: undefined: goerr.New
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/client.go:83:10: undefined: goerr.New
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/client.go:85:10: undefined: goerr.New
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/connectors.go:61:10: undefined: goerr.New
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/connectors.go:89:15: undefined: goerr.New
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/connectors.go:99:15: undefined: goerr.New
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/hset.go:14:10: undefined: goerr.NewError
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/hset.go:32:14: undefined: goerr.NewError
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/hset.go:48:10: undefined: goerr.NewError
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/hset.go:65:17: undefined: goerr.NewError
/root/go/pkg/mod/github.com/seefan/gossdb@v1.1.2/hset.go:65:17: too many errors
[root@izrj9ae0538vfzkozm32m9z ssdbmain]#

**Comment by seefan** [comment]
发布2.0
