### ISSUE TITLE
并发偶尔还会出现数据串包问题

### ISSUE THREAD

**Issue by onlywsx** [seefan/gossdb#53]
明明取用户自己key的数据，偶尔会取到其他用户key的数据
gossdb.Client().HRScanArray(key, "", "", int64(limit))

**Comment by onlywsx** [comment]
limit=1 时，却能返回其他人 limit=5 的数据

**Comment by onlywsx** [comment]
err := gossdb.Start(&conf.Config{
		Host:         "127.0.0.1",
		Port:         8888,
		PoolSize:     50,
		MaxPoolSize:  500,
		AutoClose:    true,
		RetryEnabled: true,
	})

**Comment by seefan** [comment]
收到，会再仔细分析一下

**Comment by seefan** [comment]
已经查到问题点，使用自动关闭时会有点问题，可以临时使用NewClient()创建连接，再手动关闭解决这个问题

**Comment by zut** [comment]
> 问题应该已修正

期待更新发布。

**Comment by yxlwfds** [comment]
期待新版
