### ISSUE TITLE
HScan 执行时间超长 [Linux平台]

### ISSUE THREAD

**Issue by zut** [seefan/gossdb#61]
数据库是同一个

在macOS平台, 执行 HScan(大约1000多个数据,)只需要100ms
但是在Linux(Centos7/8, Debian 8/10, ubuntu 20.04/18.04/16.04)都需要 15s左右

**Comment by seefan** [comment]
暂时没有发现这个情况哦，能不能给个示例

**Comment by zut** [comment]
> 暂时没有发现这个情况哦，能不能给个示例

```golang
c, err := gossdb.NewClient()
r c.Close()
kMapV, err := c.HScan(name, keyStart,  keyEnd, int64(limit))
```
就这一段,

**Comment by seefan** [comment]
这个问题不限于平台，主要和value大小有关，已解决
