### ISSUE TITLE
隐藏连接池相关操作

### ISSUE THREAD

**Issue by shhch** [seefan/gossdb#62]
现有的连接池要服务自己去获取连接和归还连接，这一步对服务而言有点多余，能不能将获取与归还的操作转移到具体命令函数中，让连接的使用对用户无感知？

**Comment by seefan** [comment]
使用这个方式就可以了

if v, err := gossdb.Client().Get("a"); err == nil {
	println(v.String())
} else {
	println(err.Error())
}

**Comment by shhch** [comment]
好像是我使用的是v1.1.2版本的问题，但是使用go get无法拉取到v2.0版本，有点奇怪

**Comment by shhch** [comment]
![image](https://user-images.githubusercontent.com/46923522/109266673-4f174880-7843-11eb-9d3c-0a94c852a050.png)
