### ISSUE TITLE
这个zset size 是9w+，这个命令要花20秒，java同样的demo程序花220ms，why

### ISSUE THREAD

**Issue by fuweibin** [seefan/gossdb#67]
![image](https://user-images.githubusercontent.com/9374802/187913880-75fecfc8-236a-44a0-926d-c1591da914e6.png)
这个zset size 是9w+，这个命令要花20秒，java同样的demo程序花220ms
在源码打日志,卡住 do的recv

**Comment by seefan** [comment]
//connection read buffer, default 8k, in kb
	//连接读缓冲，默认为8k，单位为kb
	ReadBufferSize int
你可以调整一个这个参数

**Comment by seefan** [comment]
重新优化了代码，修复了超大value读取速度慢的问题
